### ISSUE TITLE
No such file or directory: 'x-appl-version.txt

### ISSUE THREAD

**Issue by SeaXen** [sizifart/CEX.IO-Bot#11]
help me to solve this 

`Traceback (most recent call last):
  File "D:\TG\BOT\#Try Again\CEX.IO-Bot\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\TG\BOT\#Try Again\CEX.IO-Bot\main.py", line 8, in main
    await process()
  File "D:\TG\BOT\#Try Again\CEX.IO-Bot\bot\utils\launcher.py", line 127, in process
    await run_tasks(tg_clients=tg_clients)
  File "D:\TG\BOT\#Try Again\CEX.IO-Bot\bot\utils\launcher.py", line 133, in run_tasks
    with open("x-appl-version.txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'x-appl-version.txt'`

**Comment by samdsgn** [comment]
there bot/utils/launcher.py
change to https://cexp3.cex.io/static/js/main.86252fe0.js
