### ISSUE TITLE
how to fix sir?

### ISSUE THREAD

**Issue by stavfu** [sizifart/CEX.IO-Bot#8]
> 1
2024-09-06 09:33:15 | INFO     | 459 - pertama1 | Update auth token...
2024-09-06 09:33:15 | INFO     | 60 - Getting data for pertama1
2024-09-06 09:33:26 | INFO     | 466 - Session stavfu  logged in.
Traceback (most recent call last):
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1073, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1058, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 964, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 722, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 837, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 624, in finish_connect
    ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\bot\core\tapper.py", line 468, in run
    await self.get_user_info(http_client, authToken)
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\bot\core\tapper.py", line 139, in get_user_info
    response = await http_client.post(api_profile, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiocfscrape\__init__.py", line 79, in _request
    resp = await super()._request(method, url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiohttp\client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dani\Desktop\sc\ev\CEX.IO-Bot-main\venv\Lib\site-packages\aiohttp\connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host cexp.cex.io:443 ssl:default [The semaphore timeout period has expired]
2024-09-06 09:33:47 | ERROR    | 532 - pertama1 | Unknown error: Cannot connect to host cexp.cex.io:443 ssl:default [The semaphore timeout period has expired]

**Comment by copycatcodex** [comment]
use or try proxy vpn if u in indonesia
